name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        CC:
          - gcc
          - clang
        PARAMS:
          - ""
          - "-DFORCE_EXTERNAL_LIBEV=ON"
          - "-DBUILD_STATIC_BINARY=ON"
          - "-DBUILD_STATIC_BINARY=ON -DFORCE_EXTERNAL_LIBEV=ON"
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        run: sudo apt-get -qq update && sudo apt-get install -y libev-dev

      - name: Configure
        run: CC=${{ matrix.CC }} cmake -S . -B build ${{ matrix.PARAMS }}

      - name: Build
        run: cmake --build build

      - name: Smoke test
        run: ./build/tiny-ssh-honeypot --help

      - name: Run ldd
        run: ldd ./build/tiny-ssh-honeypot || true

      - name: Strip the binary
        run: strip ./build/tiny-ssh-honeypot

      - name: Run file
        run: file ./build/tiny-ssh-honeypot

      - name: Run ls
        run: ls -l ./build/tiny-ssh-honeypot

  build-macos:
    name: Build (MacOS)
    runs-on: macos-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Smoke test
        run: ./build/tiny-ssh-honeypot --help

      - name: Strip the binary
        run: strip ./build/tiny-ssh-honeypot

      - name: Run file
        run: file ./build/tiny-ssh-honeypot

      - name: Run ls
        run: ls -l ./build/tiny-ssh-honeypot

  build-macos-arm64:
    name: Build (MacOS ARM64)
    runs-on: macos-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=toolchain
        env:
          ARCHITECTURE: arm64
          HOSTSPEC: aarch64-apple-darwin20.0.0

      - name: Build
        run: cmake --build build

      - name: Run file
        run: file ./build/tiny-ssh-honeypot

      - name: Run ls
        run: ls -l ./build/tiny-ssh-honeypot
